config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => "/cable"
  root "home_pages#index"
  get '/404', :to => redirect("/404.html")
  get "pages/:page", to: "home_pages#show", as: :page


  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  namespace :my_page do
    resource :profile, only: [:edit, :update]
    resource :account, only: [:edit, :update]
    resource :password, only: [:edit, :update]
    resources :reports, only: [:index, :destroy]
    resources :notifications, only: [:index, :update]
  end

  resources :reviews, only: [:edit, :update, :destroy] do
    scope module: :review do
      resources :comments, only: [:index, :new, :create]
      resource :votes, only: [:create, :destroy]
    end
  end

  resources :comments, only: [:edit, :update, :destroy]
  resources :reports, only: [:new, :create]

  namespace :management do
    resources :branches, except: :destroy
    resources :review_verifications, only: [:index, :update]
    resource :center, only: [:edit, :update]
    resources :courses, except: [:show, :destroy]
    namespace :verification do
      resources :reviews, only: [:index, :update]
    end
    resource :dashboard, only: :show
  end

  namespace :supports do
    resources :districts, only: :index
    resources :categories, only: :index
  end

  namespace :search do
    resources :centers, only: :index
    resources :url_makers, only: :index
  end

  resources :users, only: :show do
    scope module: :user do
      resources :reviews, only: :index
    end
  end

  namespace :ft_search do
    resources :centers, only: :index
  end
end

app/models/branch.rb
class Branch < ApplicationRecord
  ATTRIBUTES = [:name, :city_id, :district_id, :address, :phone_number, :email]

  belongs_to :center
  belongs_to :city
  belongs_to :district
  has_many :reviews

  validates :name, presence: true, length: {maximum: Settings.validations.branch.name.max_length}
  validates :city_id, :district_id, presence: true
  validates :address, presence: true, length: {maximum: Settings.validations.branch.address.max_length}
  validates :phone_number, presence: true, phone_number_format: true
  validates :email, email_format: true

  before_save :geocode, if: :require_geocode?

  scope :order_name_asc, ->{order name: :asc}

  enum status: [:active, :inactive]

  acts_as_url :name, url_attribute: :slug, scope: :center_id, sync_url: true,
    callback_method: :before_save

  delegate :name, :route_params, to: :center, prefix: true, allow_nil: true
  delegate :name, to: :city, prefix: true, allow_nil: true
  delegate :name, to: :district, prefix: true, allow_nil: true

  geocoded_by :full_address

  friendly_findable :slug

  def full_address
    [address, district_name, city_name].join ", "
  end

  def route_params
    center.route_params.merge branch_slug: slug
  end

  private
  def require_geocode?
    errors.blank? && (address_changed? || city_id_changed? || district_id_changed?)
  end
end

app/models/center_management.rb
class CenterManagement < ApplicationRecord
  belongs_to :center
  belongs_to :user
end

app/models/supports/branch.rb
class Supports::Branch
  attr_reader :branch

  def initialize branch
    @branch = branch
  end

  def city_options
    @city_options ||= City.priority_desc.pluck :name, :id
  end

  def district_options
    @district_options ||= if branch.city.present?
      branch.city.districts.priority_desc.pluck :name, :id
    else
      []
    end
  end
end

app/controllers/branch/base_controller.rb
class Branch::BaseController < ApplicationController
  before_action :branch

  private
  def branch
    center = Center.active.friendly_find params[:center_slug]
    @branch = center.active_branches.friendly_find params[:branch_slug]
  end
end

app/controllers/branch/reviews_controller.rb
class Branch::ReviewsController < Branch::BaseController
  def index
    @q = displayable_reviews.ransack params[:q]
    @q.sorts = default_sorting_option if @q.sorts.empty?
    @reviews = @q.result.includes(:user).decorate
  end


  private
  def displayable_reviews
    if user_signed_in?
      @branch.reviews.verified.with_voted_type_by_user(current_user)
    else
      @branch.reviews.verified
    end
  end

  def default_sorting_option
    Review::SORTING_OPTIONS.first[:value]
  end
end

app/controllers/branches_controller.rb
class BranchesController < ApplicationController
  def show
    center = Center.active.friendly_find params[:center_slug]
    @branch = center.active_branches.friendly_find(params[:branch_slug]).decorate
  end
end

app/controllers/center/branches_controller.rb
class Center::BranchesController < Center::BaseController
  def index
    @q = center.active_branches.ransack params[:q]
    @branch_groups = @q.result.order_name_asc.includes(:center, :city, :district).decorate
      .group_by{|branch| branch.city}.sort_by{|k, v| k.priority}.reverse
    @support = Supports::Center.new center
    impressionist @center
  end
end

app/controllers/center_management/branches_controller.rb
class CenterManagement::BranchesController < CenterManagement::BaseController
  include Wicked::Wizard
  include SetupWizard

  before_action :setup_wizard, only: [:create, :update]
  before_action :center, only: [:index, :new, :create]
  before_action :branch, :authorize_edit_permission!, only: [:edit, :update]

  steps :start, :preview, :finish

  def index
    @q = current_user.managed_center.branches.ransack params[:q]
    @branches = @q.result
    @support = ::Supports::Center.new @center
  end

  def new
    @branch = @center.branches.build
    branch_support
  end

  def create
    @branch = @center.branches.build branch_params.merge status: :active
    wicked_step
  end

  def edit
    branch_support
  end

  def update
    @branch.assign_attributes branch_params
    wicked_step
  end

  private
  def branch
    @branch = Branch.friendly_find params[:id]
  end

  def authorize_edit_permission!
    authorize @branch
  end

  def branch_params
    params.require(:branch).permit Branch::ATTRIBUTES
  end

  def wicked_step
    case step
    when :start
      branch_support
      render_start_step
    when :preview
      preview_step
    when :finish
      finish_step
    end
  end

  def branch_support
    @support = Supports::Branch.new @branch
  end

  def preview_step
    if @branch.valid?
      render_wizard
    else
      branch_support
      flash.now[:failed] = t ".failed"
      render_start_step
    end
  end

  def finish_step
    if @branch.save
      flash[:success] = t ".success"
      redirect_to center_management_branches_path
    else
      branch_support
      flash.now[:failed] = t ".failed"
      render_start_step
    end
  end

  def render_start_step
    if @branch.new_record?
      render :new
    else
      render :edit
    end
  end
end

app/controllers/management/branches_controller.rb
class Management::BranchesController < Management::BaseController
  before_action :center
  before_action :branch, :authorize_edit_permission!, only: [:edit, :update]

  def index
    @q = current_user.managed_center.branches.ransack params[:q]
    @branches = @q.result.decorate
    @support = ::Supports::Center.new @center
  end

  def new
    @branch = Branch.new
    @support = Supports::Branch.new @branch
  end

  def create
    @branch = @center.branches.build branch_params.merge status: :active
    if @branch.save
      flash[:success] = t ".success"
      redirect_to management_branches_path
    else
      @support = Supports::Branch.new @branch
      flash.now[:failed] = t ".failed"
      render :new
    end
  end

  def edit
    @support = Supports::Branch.new @branch
  end

  def update
    if @branch.update_attributes branch_params
      flash[:success] = t ".success"
      redirect_to management_branches_path
    else
      @support = Supports::Branch.new @branch
      flash.now[:failed] = t ".failed"
      render :edit
    end
  end

  private
  def branch
    @branch = Branch.find params[:id]
  end

  def authorize_edit_permission!
    authorize @branch
  end

  def branch_params
    params.require(:branch).permit Branch::ATTRIBUTES
  end
end

app/helpers/branch_helper.rb
module BranchHelper
  def branch_status_options
    Branch::statuses.map {|k, v| [t(".#{k}"), v]}
  end
end

app/views/center_management/branches/edit.html.erb
<h2><%= t ".edit_branch", name: @branch.name_was %></h2>
<%= form_for [:center_management, @branch] do |f| %>
  <%= render "form", f: f %>
<% end %>

app/views/center_management/branches/index.html.erb
<%= link_to t(".create_new_branch"), new_center_management_branch_path %>
<%= render "branch_filter", q: @q, city_options: @support.city_options %>
<table class="table">
  <thead>
    <th><%= t ".index" %></th>
    <th><%= Branch.human_attribute_name :name %></th>
    <th><%= Branch.human_attribute_name :status %></th>
    <th><%= t ".action" %></th>
  </thead>
  <tbody id="branch-list">
    <%= render partial: "branch", collection: @branches, as: :branch %>
  </tbody>
</table>

app/views/center_management/branches/new.html.erb
<h2><%= t ".create_new_branch" %></h2>
<%= form_for [:center_management, @branch] do |f| %>
  <div class="form-group">
    <%= f.label :avatar, Branch.human_attribute_name(:avatar) %>
    <%= f.file_field :avatar %>
    <%= f.hidden_field :avatar_cache %>
  </div>

  <div class="form-group">
    <%= f.label :name, Branch.human_attribute_name(:name) %>
    <%= f.text_field :name %>
  </div>

  <div class="form-group">
    <%= f.label :city, Branch.human_attribute_name(:city) %>
    <%= f.select :city_id, @support.city_options, {include_blank: t(".select_city")},
      class: "city_selection" %>
  </div>

  <div class="form-group">
    <%= f.label :district, Branch.human_attribute_name(:district) %>
    <%= f.select :district_id, @support.district_options, {include_blank: t(".select_district")},
      class: "district_selection" %>
  </div>

  <div class="form-group">
    <%= f.label :address, Branch.human_attribute_name(:address) %>
    <%= f.text_field :address %>
  </div>

  <div class="form-group">
    <%= f.label :description, Branch.human_attribute_name(:description) %>
    <%= f.text_area :description %>
  </div>

  <div class="form-group">
    <%= f.label :email, Branch.human_attribute_name(:email) %>
    <%= f.email_field :email %>
  </div>

  <div class="form-group">
    <%= f.label :phone_number, Branch.human_attribute_name(:phone_number) %>
    <%= f.text_field :phone_number %>
  </div>

  <%= f.button t(".preview"), name: :step, value: :preview %>
<% end %>