config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => "/cable"
  root "home_pages#index"
  get '/404', :to => redirect("/404.html")
  get "pages/:page", to: "home_pages#show", as: :page


  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  namespace :my_page do
    resource :profile, only: [:edit, :update]
    resource :account, only: [:edit, :update]
    resource :password, only: [:edit, :update]
    resources :reports, only: [:index, :destroy]
    resources :notifications, only: [:index, :update]
  end

  resources :reviews, only: [:edit, :update, :destroy] do
    scope module: :review do
      resources :comments, only: [:index, :new, :create]
      resource :votes, only: [:create, :destroy]
    end
  end

  resources :comments, only: [:edit, :update, :destroy]
  resources :reports, only: [:new, :create]

  namespace :management do
    resources :branches, except: :destroy
    resources :review_verifications, only: [:index, :update]
    resource :center, only: [:edit, :update]
    resources :courses, except: [:show, :destroy]
    namespace :verification do
      resources :reviews, only: [:index, :update]
    end
    resource :dashboard, only: :show
  end

  namespace :supports do
    resources :districts, only: :index
    resources :categories, only: :index
  end

  namespace :search do
    resources :centers, only: :index
    resources :url_makers, only: :index
  end

  resources :users, only: :show do
    scope module: :user do
      resources :reviews, only: :index
    end
  end

  namespace :ft_search do
    resources :centers, only: :index
  end
end

app/views/layouts/shared/_center_category_search.html.erb
<%= link_to center_category[0],
  search_centers_path(center_search_form: {center_category_key_name_eq: center_category[1]}) %>

app/views/layouts/shared/_flash.html.erb
<% Settings.flash.each do |key, value| %>
  <% unless flash[key].blank? %>
    <div data-notify="container" class="col-xs-11 col-sm-4 alert animated fadeInDown alert <%= value %>" role="alert" data-notify-position="top-right" style="display: inline-block; margin: 0px auto; position: fixed; transition: all 0.5s ease-in-out; z-index: 1031; top: 20px; right: 20px; animation-iteration-count: 1;">
      <a class="close" data-dismiss="alert" href="#" aria-hidden="true" data-notify="dismiss">&times;</a>
      <span data-notify="icon"></span>
      <span data-notify="title"></span>
      <span data-notify="message">
        <%= content_for?(:flash_errors) ? yield(:flash_errors) : flash[key] %>
      </span>
      <a href="#" target="_blank" data-notify="url"></a>
    </div>
  <% end %>
<% end %>

app/views/layouts/shared/_footer.html.erb
<div class="footer">
  <div class="container">
    <div class="footer-inner">
      <div class="row justify-content-lg-center">
        <div class="col-lg-6">
          <div class="footer-content text-center padding-ver-clear">
            <div class="logo-footer">
              <div id="logo" class="logo">
                <%= link_to root_path do %>
                  <h2 class="title logo-font text-center text-default">Classy</h2>
                <% end %>
              </div>
            </div>
            <p><%= t(".app_description")%></p>
            <div class="separator"></div>
            <ul class="list-inline mb-20">
              <li class=""><i class="text-default fa fa-map-marker pr-1"></i> Trường đại học FPT, Khu công nghệ cao Hòa Lạc, Hà Nội</li>
              <li class=""><a href="tel:+00 1234567890" class="link-dark"><i class="text-default fa fa-phone pl-10 pr-1"></i> +84 963 260 895</a></li>
              <li class=""><a href="mailto:info@theproject.com" class="link-dark"><i class="text-default fa fa-envelope-o pl-10 pr-1"></i>classy.systems@gmail.com</a></li>
            </ul>
            <ul class="social-links circle animated-effect-1 margin-clear">
              <li class="facebook"><a target="_blank" href="http://www.facebook.com"><i class="fa fa-facebook"></i></a></li>
              <li class="twitter"><a target="_blank" href="http://www.twitter.com"><i class="fa fa-twitter"></i></a></li>
              <li class="googleplus"><a target="_blank" href="http://plus.google.com"><i class="fa fa-google-plus"></i></a></li>
              <li class="linkedin"><a target="_blank" href="http://www.linkedin.com"><i class="fa fa-linkedin"></i></a></li>
              <li class="xing"><a target="_blank" href="http://www.xing.com"><i class="fa fa-xing"></i></a></li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/shared/_guest_right_header.html.erb
<div class="header-second clearfix">
  <div class="main-navigation main-navigation--mega-menu  animated">
    <nav class="navbar navbar-expand-lg navbar-light navbar-right">
      <ul class="nav">
        <li>
          <%= link_to new_user_session_path, class: "btn btn-animated btn-default btn-sm mr-2" do %>
            <%= t ".log_in" %>
            <i class="fa fa-lock"></i>
          <% end %>
        </li>
        <li>
          <%= link_to new_user_registration_path, class: "btn btn-animated btn-default btn-sm" do %>
            <%= t ".sign_up" %>
            <i class="fa fa-user"></i>
          <% end %>
        </li>
      </ul>
    </nav>
  </div>
</div>

app/views/layouts/shared/_head.html.erb
<head>
  <title>Classy</title>
  <%= csrf_meta_tags %>
  <link rel="shortcut icon" href="assets/favicon.ico">
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
  <%= stylesheet_link_tag "https://cdnjs.cloudflare.com/ajax/libs/bootstrap-slider/10.0.0/css/bootstrap-slider.min.css" %>
  <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" %>

  <%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>
  <%= javascript_include_tag "https://cdnjs.cloudflare.com/ajax/libs/bootstrap-slider/10.0.0/bootstrap-slider.min.js" %>
  <%= yield :include_tag_layout %>
  <%= javascript_include_tag "#{Settings.google_map.src}?key=#{Settings.google_map.key}
    &libraries=#{Settings.google_map.libraries}&sensor=#{Settings.google_map.sensor}
    &language=#{Settings.google_map.language}&region=#{Settings.google_map.region}" %>
  <%= javascript_include_tag "https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.4.0/Chart.min.js" %>
</head>

app/views/layouts/shared/_header.html.erb
    <div class="header-container">
      <div class="header-top colored">
        <div class="container">
          <div class="row">
            <div class="col-2 col-md-5">
              <div class="header-top-first clearfix">
                <ul class="social-links circle small clearfix hidden-sm-down">
                  <li class="twitter"><a target="_blank" href="http://www.twitter.com"><i class="fa fa-twitter"></i></a></li>
                  <li class="skype"><a target="_blank" href="http://www.skype.com"><i class="fa fa-skype"></i></a></li>
                  <li class="linkedin"><a target="_blank" href="http://www.linkedin.com"><i class="fa fa-linkedin"></i></a></li>
                </ul>
              </div>
            </div>
            <div class="col-10 col-md-7">
              <div class="clearfix text-right header-top-second">
                <ul class="list-inline">
                  <li class="list-inline-item header-item"><strong class="pl-1">Liên hệ: </strong><a class="link-light" target="_blank" href="tel:+841234567890">0243 7552 999</a></li>
                  <%= link_to t(".for_business"), "/pages/business", class: "btn btn-gray-transparent btn-sm btn-business" %>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div id="sticked-navbar" class="sticky-wrapper">
        <header class="header fixed fixed-desktop clearfix">
          <div class="container">
            <div class="row">
              <div class="col-md-auto hidden-md-down pl-3">
                <div class="header-first clearfix">
                  <div id="logo" class="logo">
                    <%= link_to root_path do %>
                      <h2 class="title logo-font text-left text-default mb-2">Classy</h2>
                    <% end %>
                  </div>
                </div>
              </div>
              <div class="col-lg-auto ">
                <div class="header-second clearfix">
                  <div class="main-navigation main-navigation--mega-menu  animated">
                    <nav class="navbar navbar-expand-lg navbar-light navbar-right">
                      <ul class="navbar-nav ml-xl-auto">
                        <li class="nav-seperated"></li>
                        <li class="nav-item">
                        </li>
                        <li class="nav-item dropdown active">
                          <a href="blog-large-image-right-sidebar.html" class="nav-link dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Trung tâm</a>
                          <ul class="dropdown-menu">
                            <li class="dropdown">
                              <%= render partial: "layouts/shared/center_category_search",
                                collection: global_center_categories, as: :center_category %>
                            </li>
                          </ul>
                        </li>
                      </ul>
                    </nav>
                  </div>
                </div>
              </div>
              <div class="col-md-auto hidden-md-down">
                <form class="navbar-form" role="search" action="/ft_search/centers">
                  <div class="input-group">
                    <input type="text" class="form-control" placeholder="Nhập tên trung tâm..."
                      name="center_name" value="<%= params[:center_name] %>">
                    <div class="input-group-btn">
                      <button class="btn btn-gray m-0 btn-search" type="submit">
                        <i class="fa fa-search fa-lg" aria-hidden="true"></i>
                      </button>
                    </div>
                  </div>
                </form>
              </div>
              <div class="col-lg-auto ml-lg-auto">
                <% if user_signed_in? %>
                  <%= render "layouts/shared/member_right_header" %>
                <% else %>
                  <%= render "layouts/shared/guest_right_header" %>
                <% end %>
              </div>
            </div>
          </div>
        </header>
      </div>
    </div>

app/views/layouts/shared/_member_right_header.html.erb
<div class="header-fourth clearfix">
  <div class="main-navigation main-navigation--mega-menu  animated">
    <nav class="navbar navbar-expand-lg navbar-light navbar-right">
      <ul class="nav personal-actions">
        <li>
          <div class="btn-group notifications">
            <button type="button" id="notification_header"
              class="btn white-bg dropdown-toggle dropdown-toggle--no-caret"
              data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= render "layouts/shared/notification_icon",
                counter: current_user.unread_notification_counter %>
            </button>
            <ul class="dropdown-menu dropdown-menu-right cart dropdown-animation"
              aria-labelledby="header-drop-2" id="notification-header-list">
            </ul>
          </div>
        </li>
        <li>
          <div class="btn-group profile-actions">
            <button type="button" class="btn btn-sm white-bg dropdown-toggle dropdown-toggle-split"
              data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= image_tag current_user.avatar.small.url, class: "avatar rounded" %>
              <span class="sr-only">Toggle Dropdown</span>
            </button>
            <div class="dropdown-menu dropdown-menu-right">
              <%= link_to user_path(current_user), class: "dropdown-item" do %>
                <i class="fa fa-user pr-20"></i>
                Trang cá nhân
              <% end %>
              <%= link_to edit_my_page_profile_path, class: "dropdown-item" do %>
                <i class="fa fa-cog pr-20"></i>
                Cài đặt tài khoản
              <% end %>
              <% if current_user.center_manager? %>
                <div class="dropdown-divider"></div>
                <%= link_to center_path(current_user.managed_center.route_params), class: "dropdown-item" do %>
                  <i class="fa fa-mortar-board pr-10"></i>
                  Trung tâm của tôi
                <% end %>
                <%= link_to management_dashboard_path, class: "dropdown-item" do %>
                  <i class="fa fa-wrench pr-10" aria-hidden="true"></i>
                  Quản lý trung tâm
                <% end %>
              <% end %>

              <div class="dropdown-divider"></div>
              <%= link_to destroy_user_session_path, method: :delete, class: "dropdown-item" do %>
                <i class="fa fa-sign-out pr-20"></i>
                Đăng xuất
              <% end %>
              <a class="dropdown-item" href="#"></a>
            </div>
          </div>
        </li>
      </ul>
    </nav>
  </div>
</div>

app/views/layouts/shared/_notification_icon.html.erb
<i class="fa fa-globe fa-2x"></i>
<span id="unread_noti_count">
  <% if counter > 0 %>
    <span class="cart-count"><%= counter %></span>
  <% end %>
</span>